image:
  name: hashicorp/terraform:1.6
  entrypoint: ["/bin/sh", "-lc"]

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

before_script:
  - cd terraform
  - echo "$TF_VAR_private_key_content" > private_key.pem
  - chmod 600 private_key.pem
  - terraform --version

validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform validate

plan:
  stage: plan
  script:
    - terraform init -backend=false
    - terraform plan -var="private_key_path=private_key.pem" -out=tfplan
  artifacts:
    paths:
      - terraform/tfplan
      - terraform/.terraform
      - terraform/terraform.tfstate   # захватываем state как артефакт
    expire_in: 7 days
  only:
    - main

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -auto-approve tfplan
  only:
    - main
