image:
  name: hashicorp/terraform:1.6
  entrypoint: ["/bin/sh", "-lc"]

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

before_script:
  - cd terraform
  - echo "$TF_VAR_private_key_content" > private_key.pem
  - chmod 600 private_key.pem
  # Если tfstate нет (первый запуск), создаём его из переменной
  - '[ ! -f terraform.tfstate ] && echo "$TFSTATE_JSON" > terraform.tfstate || echo "Using existing tfstate"'

validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform validate

plan:
  stage: plan
  script:
    - terraform init -backend=false
    - terraform plan -var="private_key_path=private_key.pem" -out=tfplan
  artifacts:
    paths:
      - tfplan
      - terraform.tfstate
    expire_in: 1 hour
  only:
    - main

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -auto-approve tfplan
  artifacts:
    paths:
      - terraform.tfstate
    expire_in: 1 hour
  only:
    - main
