apiVersion: v1
kind: Service
metadata:
  name: test-nginx-app
  namespace: test-app
spec:
  type: NodePort
  selector:
    app: test-nginx-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
