name: Run Ansible on existing servers

on:
  push:
    branches: [ "main" ]

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Установка SSH ключа
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Установка Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      # Запуск Ansible Playbook с существующим inventory
      - name: Run Ansible
        working-directory: ./playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook \
            -i ../terraform/inventory.ini \
            site.yml \
            --user=${{ secrets.ANSIBLE_USERNAME }} \
            --private-key ~/.ssh/id_rsa

      - name: Final output
        run: echo "Ansible deployment complete."
